<?php
$modversion['name'] = _ALBM_FLASHGAMES_NAME;
$modversion['version'] = '1.0.1';
$modversion['description'] = _ALBM_FLASHGAMES_DESC;
$modversion['author'] = "Oliver Kaufhold (aka gripsmaker) <br> (http://www.tipsmitgrips.de)";

$modversion['credits'] = "<br>Oficial Partner<br>Lee Eason<br>(http://www.pnflashgames.com)<br>

<br>Daniel Branco<br>(http://bluetopia.homeip.net)<br>Kazumi Ono<br>( http://www.mywebaddons.com/ )<br>The XOOPS Project <br> and all 'Flashgames' Supporters!";
$modversion['help'] = "mylinks.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "images/mylinks_slogo.gif";
$modversion['dirname'] = "flashgames";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "flashgames_cat";
$modversion['tables'][1] = "flashgames_games";
$modversion['tables'][2] = "flashgames_text";
$modversion['tables'][3] = "flashgames_votedata";
$modversion['tables'][4] = "flashgames_comments";
$modversion['tables'][5] = "flashgames_score";
$modversion['tables'][6] = "flashgames_savedGames";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Blocks

$modversion['blocks'][1]['file'] = "flashgames_top.php";
$modversion['blocks'][1]['name'] = _ALBM_MYLINKS_BNAME1;
$modvertion['blocks'][1]['description'] = "Shows recently added games";
$modversion['blocks'][1]['show_func'] = "b_flashgames_top_show";
$modversion['blocks'][1]['edit_func'] = "b_flashgames_top_edit";
$modversion['blocks'][1]['options'] = "date|10";
$modversion['blocks'][1]['template'] = 'flashgames_block_new.html';

$modversion['blocks'][2]['file'] = "flashgames_top.php";
$modversion['blocks'][2]['name'] = _ALBM_MYLINKS_BNAME2;
$modvertion['blocks'][2]['description'] = "Shows most played games";
$modversion['blocks'][2]['show_func'] = "b_flashgames_top_show";
$modversion['blocks'][2]['edit_func'] = "b_flashgames_top_edit";
$modversion['blocks'][2]['options'] = "hits|10";
$modversion['blocks'][2]['template'] = 'flashgames_block_top.html';


$modversion['blocks'][3]['file'] = "flashgames_comments.php";
$modversion['blocks'][3]['name'] = _ALBM_MYGAME_COMMENTS;
$modvertion['blocks'][3]['description'] = "Shows last comments";
$modversion['blocks'][3]['show_func'] = "b_flashgames_comments_show";
$modversion['blocks'][3]['edit_func'] = "b_flashgames_comments_edit";
$modversion['blocks'][3]['options'] = "10|1";

$modversion['blocks'][4]['file'] = "flashgames_top.php";
$modversion['blocks'][4]['name'] = _ALBM_MYLINKS_BNAME3;
$modvertion['blocks'][4]['description'] = "Shows best players";
$modversion['blocks'][4]['show_func'] = "b_flashgames_topplayer_show";
$modversion['blocks'][4]['edit_func'] = "b_flashgames_topplayer_edit";
$modversion['blocks'][4]['options'] = "10";
$modversion['blocks'][4]['template'] = 'flashgames_block_topplayer.html';

$modversion['blocks'][5]['file'] = "flashgames_random.php";
$modversion['blocks'][5]['name'] = _ALBM_MYGAME_RANDOM;
$modvertion['blocks'][5]['description'] = "Shows a random game";
$modversion['blocks'][5]['show_func'] = "b_flashgames_random_show";
$modversion['blocks'][5]['edit_func'] = "b_flashgames_random_edit";
$modversion['blocks'][5]['options'] = "110|3";
$modversion['blocks'][5]['template'] = 'flashgames_block_random.html';

$modversion['blocks'][6]['file'] = "flashgames_latest.php";
$modversion['blocks'][6]['name'] = _ALBM_MYGAME_LATEST;
$modvertion['blocks'][6]['description'] = "Shows the latest game";
$modversion['blocks'][6]['show_func'] = "b_flashgames_latest_show";
$modversion['blocks'][6]['edit_func'] = "b_flashgames_latest_edit";
$modversion['blocks'][6]['options'] = "110|3";
$modversion['blocks'][6]['template'] = 'flashgames_block_latest.html';






// Menu
$modversion['hasMain'] = 1;
// please activate if you want to let user submit games
//$modversion['sub'][1]['name'] = _ALBM_MYLINKS_SMNAME1;
//$modversion['sub'][1]['url'] = "submit.php";

$modversion['sub'][1]['name'] = _ALBM_MYLINKS_SMNAME5;
$modversion['sub'][1]['url'] = "topscorers.php";
$modversion['sub'][3]['name'] = _ALBM_MYLINKS_SMNAME4;
$modversion['sub'][3]['url'] = "highscores.php";
$modversion['sub'][4]['name'] = _ALBM_MYLINKS_SMNAME2;
$modversion['sub'][4]['url'] = "topten.php?hit=1";
$modversion['sub'][5]['name'] = _ALBM_MYLINKS_SMNAME3;
$modversion['sub'][5]['url'] = "topten.php?rate=1";

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "flashgames_search";

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['itemName'] = 'lid';
$modversion['comments']['pageName'] = 'game.php';

// Templates
$modversion['templates'][1]['file'] = 'flashgames_game.html';
$modversion['templates'][1]['description'] = 'Process game';
$modversion['templates'][2]['file'] = 'flashgames_gameformat.html';
$modversion['templates'][2]['description'] = 'Game layout and highscoretable';
$modversion['templates'][3]['file'] = 'flashgames_highscores.html';
$modversion['templates'][3]['description'] = 'Show Highscores';
$modversion['templates'][4]['file'] = 'flashgames_topscorers.html';
$modversion['templates'][4]['description'] = 'Show Topscorers list';
$modversion['templates'][5]['file'] = 'flashgames_index.html';
$modversion['templates'][5]['description'] = 'Show Index';
$modversion['templates'][6]['file'] = 'flashgames_viewcat.html';
$modversion['templates'][6]['description'] = 'View Catalog';
$modversion['templates'][7]['file'] = 'flashgames_showgames.html';
$modversion['templates'][7]['description'] = 'Show list of games on a page';



?>
